In [1]:
import pandas as pd

In [5]:
data = pd.read_excel("containment.xlsx")

In [7]:
data.head(20)

,Kerala State Disaster Management Authority (KSDMA),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,"Observatory Hills, Vikas Bhavan P.O,Thiruvanan...",NaN,NaN,NaN,NaN
1,"Day time phone - 0471 2331345, 0471-2331645, N...",NaN,NaN,NaN,NaN
2,"Toll Free 1079, Fax - 0471 2364424. www.sdma.k...",NaN,NaN,NaN,NaN
3,List of Local Self Governments needing special...,NaN,NaN,NaN,NaN
4,GO (Ms) No. 18/2020/DMD dated 17-06-2020,NaN,NaN,NaN,NaN
5,Sl. No,District,LSGs needing special,Containment Zones,NaN
6,NaN,NaN,attention,NaN,NaN
7,1,Ernakulam,Aikaranad,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,",NaN
8,NaN,NaN,NaN,14 (Sub Ward),NaN
9,2,Ernakulam,Alangad,"1, 3, 4, 5, 6, 9,12, 13, 14, 15, 16,",NaN
10,NaN,NaN,NaN,"21(Sub Wards) 2, 7, 10, 11, 12, 18, 20",NaN
11,3,Ernakulam,Aluva,"6, 8, 16, 19, 24",NaN
12,4,Ernakulam,Amballur,"1, 2, 3, 4, 5,6, 7, 8, 9, 10, 11, 12, 13,",NaN
13,NaN,NaN,NaN,"14, 15, 16 (Sub Ward)",NaN
14,5,Ernakulam,Angamali,24(Sub Ward),NaN
15,6,Ernakulam,Arakuzha,"1, 5, 6(Sub Ward)",NaN
16,7,Ernakulam,Asamannur,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,",NaN
17,NaN,NaN,NaN,14,NaN
18,8,Ernakulam,Avoli,"1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,",NaN
19,NaN,NaN,NaN,14 (Sub Wards),NaN